ex1:
	gcc -c aluno.c -Wall
	gcc -c ex1.c -Wall
	gcc aluno.o ex1.o -o exe
	./exe

ex2:
	gcc -c aluno.c -Wall
	gcc -c ex2.c -Wall
	gcc aluno.o ex2.o -o exe
	./exe

ex3:
	gcc -c aluno.c -Wall
	gcc -c ex3.c -Wall
	gcc aluno.o ex3.o -o exe
	./exe

ex4:
	gcc -c aluno.c -Wall
	gcc -c ex4.c -Wall
	gcc aluno.o ex4.o -o exe
	./exe

ex5:
	gcc -c aluno.c -Wall
	gcc -c ex5.c -Wall
	gcc aluno.o ex5.o -o exe
	./exe

clear:
	clear
	rm *.o exe conceitos.txt